/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab;
import java.awt.*; 
import java.awt.event.*;
import javax.swing.*; 
import java.sql.*;
/**
 *
 * @author thegr
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        
        initComponents();
        //setSize(150,150);
        jTextField1 = new JTextField(20);
        jTextArea1 = new JTextArea(10,20);
        jButton1 =new JButton("Ejecutar SQL");
        JScrollPane scrollPanel = new JScrollPane(jTextArea1);
        jButton1.addActionListener((ActionListener) this);
        JPanel Panel1 = new JPanel();
        //PanelDatos.setLayout(new GridLayout(0, 1));
        Panel1.setLayout(new BoxLayout(Panel1,BoxLayout.Y_AXIS));
        Panel1.add(Box.createRigidArea(new Dimension(30,10)));
        Panel1.add(jTextField1);
        Panel1.add(Box.createRigidArea(new Dimension(30,10)));
        //PanelDatos.add(areaResultados);
        //Panel1.add(scrollPanel);
        JPanel Panel2 = new JPanel();

        //SubPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        //SubPanel.setLayout(new BorderLayout());
        Panel2.setLayout(new BoxLayout(Panel2,BoxLayout.Y_AXIS));
        //SubPanel.add(PanelDatos);
        Panel2.add(Box.createRigidArea(new Dimension(30,10)));
        Panel2.add(scrollPanel);
        //SubPanel.add(scrollPanel,"South");
        Panel2.add(Box.createRigidArea(new Dimension(30,10)));
        Panel2.add(jButton1);
        Panel2.add(Box.createRigidArea(new Dimension(30,10)));
        JPanel Panel = new JPanel();

        //SubPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        //SubPanel.setLayout(new BorderLayout());
        Panel.setLayout(new BoxLayout(Panel,BoxLayout.Y_AXIS));
        //SubPanel.add(PanelDatos);
        Panel.add(Panel1);
        //SubPanel.add(scrollPanel,"South");
        Panel.add(Panel2);
        getContentPane().add(Panel,BorderLayout.CENTER);
        //addWindowListener(new EventosVentana(this));
    }
    
    void verBaseDatos()
    {
      try
      {
           //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           Class.forName("com.mysql.jdbc.Driver").newInstance();
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/EmpresaMSQL","root","root");
           //Connection conexion = DriverManager.getConnection("jdbc:odbc:Empresa");
           Statement sentencia = conexion.createStatement();
           //boolean tieneResultados=sentencia.execute(txtSql.getText());
           boolean tieneResultados=sentencia.execute("select * from productos");
           if(tieneResultados)
           {
             ResultSet resultado = sentencia.getResultSet();
             if (resultado != null)
             {
               mostrarResultados(resultado);
             }
             else
             {
               jTextArea1.setText("");
             }
             conexion.close();
           }
      }
      catch(ClassNotFoundException e){
           System.out.println("Controlador no Encontrado: "+e);
      }
      catch(Exception e){
           System.out.println("Error de Conexión "+e);
      }
    }
    
    void mostrarResultados(ResultSet r) throws SQLException
    {
           ResultSetMetaData res = r.getMetaData(); 
           int numCampos = res.getColumnCount();
           String texto=""; 
           for(int i=1;i<=numCampos;i++)
           {
             if(i<numCampos)
             {
               texto+=res.getColumnName(i)+" \t";
             } else
             {
               texto+=res.getColumnName(i);
             }
           }
           texto+="\n";
           //texto+="-";
           texto+="\t";
           texto+="\n";
           while(r.next())
           {
             for(int j=1;j<=numCampos;j++){
               if(j<=numCampos){
                   texto+=r.getString(j)+" \t";
               } else {
                   texto+=r.getString(j).trim();
               }
             } 
             texto+= "\n";
           }
           jTextArea1.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setName("txtSql"); // NOI18N

        jScrollPane1.setName("scrollPanel"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("areaResultados"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Ejecutar");
        jButton1.setName("btnConsulta"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese consulta: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        verBaseDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventana2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
