/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab;
import java.awt.*; import java.awt.event.*;
import javax.swing.*; import java.sql.*;
/**
 *
 * @author thegr
 */
public class Ventana extends javax.swing.JFrame {

    JTextField txtSql;
    JTextArea areaResultados;
    JButton btnConsulta;

    /**
     * Creates new form Ventana
     */
    public Ventana(String titulo) {
        super(titulo);
        //setSize(150,150);
        txtSql = new JTextField(20);
        areaResultados = new JTextArea(10,20);
        btnConsulta =new JButton("Ejecutar SQL");
        JScrollPane scrollPanel = new JScrollPane(areaResultados);
        btnConsulta.addActionListener(new EventoBoton(this));
        JPanel Panel1 = new JPanel();
        //PanelDatos.setLayout(new GridLayout(0, 1));
        Panel1.setLayout(new BoxLayout(Panel1,BoxLayout.Y_AXIS));
        Panel1.add(Box.createRigidArea(new Dimension(30,10)));
        Panel1.add(txtSql);
        Panel1.add(Box.createRigidArea(new Dimension(30,10)));
        //PanelDatos.add(areaResultados);
        //Panel1.add(scrollPanel);
        JPanel Panel2 = new JPanel();

        //SubPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        //SubPanel.setLayout(new BorderLayout());
        Panel2.setLayout(new BoxLayout(Panel2,BoxLayout.Y_AXIS));
        //SubPanel.add(PanelDatos);
        Panel2.add(Box.createRigidArea(new Dimension(30,10)));
        Panel2.add(scrollPanel);
        //SubPanel.add(scrollPanel,"South");
        Panel2.add(Box.createRigidArea(new Dimension(30,10)));
        Panel2.add(btnConsulta);
        Panel2.add(Box.createRigidArea(new Dimension(30,10)));
        JPanel Panel = new JPanel();

        //SubPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        //SubPanel.setLayout(new BorderLayout());
        Panel.setLayout(new BoxLayout(Panel,BoxLayout.Y_AXIS));
        //SubPanel.add(PanelDatos);
        Panel.add(Panel1);
        //SubPanel.add(scrollPanel,"South");
        Panel.add(Panel2);
        getContentPane().add(Panel,BorderLayout.CENTER);
        addWindowListener(new EventosVentana(this));
        initComponents();
    }
    void verBaseDatos()
    {
      try
      {
           //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           Class.forName("com.mysql.jdbc.Driver").newInstance();
           Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/EmpresaMSQL","root","root");
           //Connection conexion = DriverManager.getConnection("jdbc:odbc:Empresa");
           Statement sentencia = conexion.createStatement();
           //boolean tieneResultados=sentencia.execute(txtSql.getText());
           boolean tieneResultados=sentencia.execute(“select * from
           productos”);
           if(tieneResultados)
           {
             ResultSet resultado = sentencia.getResultSet();
             if (resultado != null)
             {
               mostrarResultados(resultado);
             }
             else
             {
               areaResultados.setText("");
             }
             conexion.close();
           }
      }
      catch(ClassNotFoundException e){
           System.out.println("Controlador no Encontrado: "+e);
      }
      catch(Exception e){
           System.out.println("Error de Conexión "+e);
      }
    }
    void mostrarResultados(ResultSet r) throws SQLException
    {
           ResultSetMetaData res = r.getMetaData(); int numCampos = res.getColumnCount();
           String texto=""; 
           for(int i=1;i<=numCampos;i++)
           {
             if(i<numCampos)
             {
               texto+=res.getColumnName(i)+" \t";
             } else
             {
               texto+=res.getColumnName(i);
             }
           }
           texto+="\n";
           //texto+="-";
           texto+="\t";
           texto+="\n";
           while(r.next())
           {
             for(int j=1;j<=numCampos;j++){
               if(j<=numCampos){
                   texto+=r.getString(j)+" \t";
               } else {
                   texto+=r.getString(j).trim();
               }
             } 
             texto+= "\n";
           }
           areaResultados.setText(texto);
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setName("txtSql"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Ejecutar SQL");
        jButton1.setName("btnConsulta"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("areaResultados"); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana("Prueba").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
